use std::env::args;
use std::path::PathBuf;

use anyhow::Result;

use crate::model::{
    AutoGeneratedVariable, Block, Comment, SimpleVariable, VariableWithRandomValue, Variables,
};
use crate::parser::Parser;

mod model;
mod parser;

fn main() -> Result<()> {
    if let Some(path) = args().nth(1) {
        let mut parser = Parser::new(PathBuf::from(path))?;
        parser.parse()?;
        return Ok(());
    }

    let title = Comment::new("42");
    let description = Some(Comment::new("Fourty-two"));

    let mut variable1 = SimpleVariable::new("ANSWER", None, None);
    variable1.user_input("42");
    let mut variable2 = SimpleVariable::new("AS_TEXT", None, None);
    variable2.user_input("fourty two");
    let variable3 = SimpleVariable::new("DEFAULT_VALUE_ONE", Some("default value"), None);
    let mut variable4 = SimpleVariable::new("DEFAULT_VALUE_TWO", Some("default"), None);
    variable4.user_input("custom");
    let variable5 = VariableWithRandomValue::new("SECRET_KEY", None);
    let variable6 = AutoGeneratedVariable::new("AUTO_GENERATED", "{ANSWER}-{DEFAULT_VALUE_ONE}");

    let variables = vec![
        Variables::Input(variable1),
        Variables::Input(variable2),
        Variables::Input(variable3),
        Variables::Input(variable4),
        Variables::Random(variable5),
        Variables::AutoGenerated(variable6),
    ];
    let block = Block::new(title, description, variables);
    println!("{block}");
    Ok(())
}
